import {NextRequest,NextResponse} from "next/server";
import {db} from "@/lib/supabase";
const TG=()=>process.env.TELEGRAM_BOT_TOKEN!;
async function tg(method:string,body:any){const r=await fetch("https://api.telegram.org/bot"+TG()+"/"+method,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});return r.json()}
async function send(chat_id:number,text:string,keyboard?:any){return tg("sendMessage",{chat_id,text,parse_mode:"HTML",reply_markup:keyboard?{inline_keyboard:keyboard}:undefined})}
function menu(){return [[{text:"🛍️ Commander un produit",callback_data:"product"},{text:"📦 Faire acheminer un colis",callback_data:"transit"}],[{text:"🔎 Suivre ma commande",callback_data:"track"},{text:"💬 Contacter YEDEM GROUP",callback_data:"contact"}]]}
export async function POST(req:NextRequest){try{const u=await req.json();const m=u.message;const c=u.callback_query;const chat=m?.chat?.id??c?.message?.chat?.id;const from=m?.from??c?.from;if(!chat)return NextResponse.json({ok:true});const sup=db();let {data:s}=await sup.from("bot_sessions").select("*").eq("telegram_chat_id",chat).maybeSingle();if(!s){const ins=await sup.from("bot_sessions").insert({telegram_chat_id:chat,telegram_user_id:from?.id,state:"idle",data:{}}).select().single();s=ins.data}
if(c){await tg("answerCallbackQuery",{callback_query_id:c.id});const a=c.data;if(a==="product"){await sup.from("bot_sessions").update({state:"product_photo",data:{}}).eq("telegram_chat_id",chat);return await send(chat,"📸 <b>Envoyez-moi la photo du produit</b> que vous souhaitez commander.");}if(a==="transit"){await sup.from("bot_sessions").update({state:"transit_type",data:{}}).eq("telegram_chat_id",chat);return await send(chat,"📦 Quel type de colis souhaitez-vous faire acheminer ?");}if(a==="track"){await sup.from("bot_sessions").update({state:"track_number",data:{}}).eq("telegram_chat_id",chat);return await send(chat,"🔎 Envoyez votre numéro de commande, par exemple <b>YD-000001</b>.");}if(a==="contact")return await send(chat,"💬 Écrivez votre message ici. L’équipe YEDEM GROUP vous répondra dès que possible.");if(a==="confirm"){const d=s.data||{};const order=await sup.from("orders").insert({telegram_chat_id:chat,telegram_user_id:from?.id,status:"a_rechercher",quantity:d.quantity,size:d.size,color:d.color,budget_max:d.budget_max,delivery_city:d.delivery_city,whatsapp:d.whatsapp,notes:d.notes}).select().single();if(order.error)throw order.error;const number=order.data.order_number;await sup.from("bot_sessions").update({state:"idle",data:{}}).eq("telegram_chat_id",chat);await send(chat,"✅ <b>Demande reçue !</b>\n\nVotre numéro de commande : <b>"+number+"</b>\n\nYEDEM GROUP va rechercher le produit et calculer son coût d’acheminement. Nous vous communiquerons le prix total avant toute commande.",menu());return NextResponse.json({ok:true})}if(a==="cancel"){await sup.from("bot_sessions").update({state:"idle",data:{}}).eq("telegram_chat_id",chat);return send(chat,"Demande annulée.",menu())}}
if(m?.text==="/start"){await sup.from("bot_sessions").update({state:"idle",data:{}}).eq("telegram_chat_id",chat);return send(chat,"👋 <b>Bienvenue chez YEDEM GROUP</b>\n\nCommandez un produit à l’étranger ou faites étudier l’acheminement d’un colis vers la Côte d’Ivoire.",menu())}
if(m?.text==="/menu"){return send(chat,"Choisissez une option :",menu())}
const state=s.state;const d={...(s.data||{})};
if(state==="product_photo"&&m.photo){d.photo=m.photo.at(-1).file_id;await sup.from("bot_sessions").update({state:"product_quantity",data:d}).eq("telegram_chat_id",chat);return send(chat,"👍 Photo reçue.\n\nQuelle quantité souhaitez-vous ?");}
if(state==="product_quantity"){d.quantity=Math.max(1,parseInt(m.text||"1")||1);await sup.from("bot_sessions").update({state:"product_size",data:d}).eq("telegram_chat_id",chat);return send(chat,"📏 Quelle taille ? Écrivez <b>aucune</b> si ce n’est pas nécessaire.");}
if(state==="product_size"){d.size=(m.text||"").trim();await sup.from("bot_sessions").update({state:"product_color",data:d}).eq("telegram_chat_id",chat);return send(chat,"🎨 Quelle couleur ou modèle ? Écrivez <b>aucun</b> si ce n’est pas nécessaire.");}
if(state==="product_color"){d.color=(m.text||"").trim();await sup.from("bot_sessions").update({state:"product_budget",data:d}).eq("telegram_chat_id",chat);return send(chat,"💰 Quel est votre budget maximum ? Écrivez <b>aucun</b> si vous ne souhaitez pas préciser.");}
if(state==="product_budget"){d.budget_max=(m.text||"").trim();await sup.from("bot_sessions").update({state:"product_city",data:d}).eq("telegram_chat_id",chat);return send(chat,"📍 Dans quelle ville souhaitez-vous être livré ?");}
if(state==="product_city"){d.delivery_city=(m.text||"").trim();await sup.from("bot_sessions").update({state:"product_whatsapp",data:d}).eq("telegram_chat_id",chat);return send(chat,"📱 Quel numéro WhatsApp pouvons-nous utiliser pour vous contacter ?");}
if(state==="product_whatsapp"){d.whatsapp=(m.text||"").trim();await sup.from("bot_sessions").update({state:"product_notes",data:d}).eq("telegram_chat_id",chat);return send(chat,"📝 Une précision à ajouter ? Écrivez-la ou <b>aucune</b>.");}
if(state==="product_notes"){d.notes=(m.text||"").trim();await sup.from("bot_sessions").update({state:"confirm_product",data:d}).eq("telegram_chat_id",chat);return send(chat,"📋 <b>Récapitulatif</b>\n\nQuantité : "+d.quantity+"\nTaille : "+d.size+"\nCouleur/modèle : "+d.color+"\nBudget : "+d.budget_max+"\nVille : "+d.delivery_city+"\nWhatsApp : "+d.whatsapp+"\n\nConfirmez-vous la demande ?",[[{text:"✅ Confirmer",callback_data:"confirm"},{text:"❌ Annuler",callback_data:"cancel"}]])}
if(state==="transit_type"){d.type=m.text;await sup.from("bot_sessions").update({state:"transit_origin",data:d}).eq("telegram_chat_id",chat);return send(chat,"🌍 Pays et ville d’origine du colis ?");}
if(state==="transit_origin"){d.origin=m.text;await sup.from("bot_sessions").update({state:"transit_weight",data:d}).eq("telegram_chat_id",chat);return send(chat,"⚖️ Poids ou volume approximatif, si vous le connaissez ?");}
if(state==="transit_weight"){d.weight=m.text;await sup.from("bot_sessions").update({state:"transit_city",data:d}).eq("telegram_chat_id",chat);return send(chat,"📍 Ville de destination en Côte d’Ivoire ?");}
if(state==="transit_city"){d.delivery_city=m.text;await sup.from("bot_sessions").update({state:"transit_whatsapp",data:d}).eq("telegram_chat_id",chat);return send(chat,"📱 Votre numéro WhatsApp ?");}
if(state==="transit_whatsapp"){d.whatsapp=m.text;const r=await sup.from("orders").insert({telegram_chat_id:chat,telegram_user_id:from?.id,status:"a_etudier",delivery_city:d.delivery_city,whatsapp:d.whatsapp,notes:"Acheminement | Type: "+d.type+" | Origine: "+d.origin+" | Poids/volume: "+d.weight}).select().single();if(r.error)throw r.error;await sup.from("bot_sessions").update({state:"idle",data:{}}).eq("telegram_chat_id",chat);return send(chat,"✅ <b>Demande d’acheminement reçue.</b>\nNuméro : <b>"+r.data.order_number+"</b>\n\nNous allons étudier votre demande et revenir vers vous.",menu())}
if(state==="track_number"){const r=await sup.from("orders").select("order_number,status,updated_at").eq("order_number",(m.text||"").trim().toUpperCase()).maybeSingle();if(!r.data)return send(chat,"❌ Commande introuvable. Vérifiez le numéro et réessayez.");return send(chat,"🔎 <b>"+r.data.order_number+"</b>\nStatut : <b>"+r.data.status+"</b>\nDernière mise à jour : "+new Date(r.data.updated_at).toLocaleString("fr-FR"));}
if(m?.text)return send(chat,"Utilisez /menu pour choisir une action.",menu());return NextResponse.json({ok:true})}catch(e){console.error(e);return NextResponse.json({ok:false},{status:500})}}